### ISSUE TITLE
Issue while enabling ( my plugin ) using simp API make the plugin crashes

### ISSUE THREAD

**Issue by Le-noirrateur** [Cortex-MC/SimpAPI#34]
Hello, i had a problem with starting my plugin, it's using Simp API for creating commands but the plugin start to crash **when it's try to enable.**

- Here the error code : 

```
[17:18:29 ERROR]: Could not load 'plugins\MCE-PVP-Server-1.18-Alpha-prebeta.jar' in folder 'plugins'
org.bukkit.plugin.InvalidPluginException: java.lang.NoClassDefFoundError: me/kodysimpson/simpapi/command/CommandList
	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:149) ~[spigot-api-1.19.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:394) ~[spigot-api-1.19.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:301) ~[spigot-api-1.19.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_19_R1.CraftServer.loadPlugins(CraftServer.java:414) ~[spigot-1.19.2-R0.1-SNAPSHOT.jar:3610-Spigot-6198b5a-19df23a]
	at org.bukkit.craftbukkit.v1_19_R1.CraftServer.reload(CraftServer.java:922) ~[spigot-1.19.2-R0.1-SNAPSHOT.jar:3610-Spigot-6198b5a-19df23a]
	at org.bukkit.Bukkit.reload(Bukkit.java:802) ~[spigot-api-1.19.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.command.defaults.ReloadCommand.execute(ReloadCommand.java:27) ~[spigot-api-1.19.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:149) ~[spigot-api-1.19.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_19_R1.CraftServer.dispatchCommand(CraftServer.java:833) ~[spigot-1.19.2-R0.1-SNAPSHOT.jar:3610-Spigot-6198b5a-19df23a]
	at org.bukkit.craftbukkit.v1_19_R1.CraftServer.dispatchServerCommand(CraftServer.java:818) ~[spigot-1.19.2-R0.1-SNAPSHOT.jar:3610-Spigot-6198b5a-19df23a]
	at net.minecraft.server.dedicated.DedicatedServer.bg(DedicatedServer.java:419) ~[spigot-1.19.2-R0.1-SNAPSHOT.jar:3610-Spigot-6198b5a-19df23a]
	at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:395) ~[spigot-1.19.2-R0.1-SNAPSHOT.jar:3610-Spigot-6198b5a-19df23a]
	at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1197) ~[spigot-1.19.2-R0.1-SNAPSHOT.jar:3610-Spigot-6198b5a-19df23a]
	at net.minecraft.server.MinecraftServer.v(MinecraftServer.java:1013) ~[spigot-1.19.2-R0.1-SNAPSHOT.jar:3610-Spigot-6198b5a-19df23a]
	at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:293) ~[spigot-1.19.2-R0.1-SNAPSHOT.jar:3610-Spigot-6198b5a-19df23a]
	at java.lang.Thread.run(Thread.java:1589) [?:?]
Caused by: java.lang.NoClassDefFoundError: me/kodysimpson/simpapi/command/CommandList
	at java.lang.Class.forName0(Native Method) ~[?:?]
	at java.lang.Class.forName(Class.java:495) ~[?:?]
	at java.lang.Class.forName(Class.java:474) ~[?:?]
	at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:67) ~[spigot-api-1.19.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:145) ~[spigot-api-1.19.2-R0.1-SNAPSHOT.jar:?]
	... 15 more
Caused by: java.lang.ClassNotFoundException: me.kodysimpson.simpapi.command.CommandList
	at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:147) ~[spigot-api-1.19.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:99) ~[spigot-api-1.19.2-R0.1-SNAPSHOT.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:521) ~[?:?]
	at java.lang.Class.forName0(Native Method) ~[?:?]
	at java.lang.Class.forName(Class.java:495) ~[?:?]
	at java.lang.Class.forName(Class.java:474) ~[?:?]
	at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:67) ~[spigot-api-1.19.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:145) ~[spigot-api-1.19.2-R0.1-SNAPSHOT.jar:?]
	... 15 more

```

- Code using **simp API** : 

Main plugin java : 

```Java
try {
       CommandManager.createCoreCommand(this, "create", "Créer une note.", "/create", new CommandList() {
           @Override
           public void displayCommandList(CommandSender p, List<SubCommand> list) {
               p.sendMessage("---");
               for (SubCommand subCommand : list) {
                   p.sendMessage(subCommand.getSyntax() + " - " + subCommand.getDescription());
               }
               p.sendMessage("---");
           }
       }, createnote.class);
} catch (NoSuchFieldException e) {
       throw new RuntimeException(e);
} catch (IllegalAccessException e) {
       throw new RuntimeException(e);
}
```
        
the command : 

```Java
package net.mceteams.plugininpvp.commands;

import me.kodysimpson.simpapi.command.SubCommand;
import net.mceteams.plugininpvp.utils.DataStorageUtil;
import org.bukkit.Bukkit;
import org.bukkit.command.CommandSender;
import org.bukkit.entity.Player;

import java.util.List;


public class createnote extends SubCommand {

    @Override
    public String getName() {
        return "create";
    }

    @Override
    public List<String> getAliases() {
        return null;
    }

    @Override
    public String getDescription() {
        return "Créer une note";
    }

    @Override
    public String getSyntax() {
        return "/create note <message> <id>";
    }

    @Override
    public void perform(CommandSender commandSender, String[] args) {
        if (args.length > 0) {
            StringBuilder stringBuilder = new StringBuilder();
            Player p = Bukkit.getPlayer(commandSender.getName());

            for (int i = 0; i < (args.length - 1); i++){
                stringBuilder.append(args[i]).append(" ");
            }
            stringBuilder.append(args[args.length - 1]);

            if (p != null) {
                DataStorageUtil.createNote(p, stringBuilder.toString(), p.getUniqueId().toString());
            }
        }
    }

    @Override
    public List<String> getSubcommandArguments(Player player, String[] strings) {
        return null;
    }
}
```

- Configuration :

Version Minecraft : 1.19.2 - Spigot Bukkit.
Code : Meaven.
Api Version : 1.19.
Simp API : from 4.3.2 to 4.4.0.
Server launched in : Windows 11 Pro, RAM 16 Go, Intel Core I5 9600 KF.
Java Version used : Jre 17.

- Other :

I don't know if the error come from my plugin in, i hope it's not but actually it's annoying to having issue with it because it's work pretty well and it's help a lot.

Hope you'll will be able to help me.

**Comment by JourBoon** [comment]
Hi, I had this problem with my own API, this error is triggered when your plugin doesn't compile with the API.
Can you show up your pom.xml? Try using 'mvn install' when compiling your plugin or add the scope in your dependence -> ```<scope>compile</scope>```. It should work. I hope this helped you :)
Sorry for my bad english I'm french

**Comment by Le-noirrateur** [comment]
> Hi, I had this problem with my own API, this error is triggered when your plugin doesn't compile with the API. Can you show up your pom.xml? Try using 'mvn install' when compiling your plugin or add the scope in your dependence -> `<scope>compile</scope>`. It should work. I hope this helped you :) Sorry for my bad english I'm french

J'ai essayé autre chose ( je suis français aussi ) j'ai abandonnée l'idée d'utiliser Simp API.
